<?php

namespace AppBundle\Repository;

/**
 * FavoriproductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavoriproductRepository extends \Doctrine\ORM\EntityRepository
{
}
