<?php

namespace AppBundle\Repository;

/**
 * PromoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromoRepository extends \Doctrine\ORM\EntityRepository
{
    public  function getLastPromo(){
        $date=new \DateTime('now');
        $em=$this->getEntityManager();
        $query=$em->createQuery('SELECT p FROM AppBundle:Promo p
          WHERE p.datedebut > CURRENT_DATE() ')
            ->setMaxResults(1);
        /*$query = $em->createQuery('SELECT d FROM test d WHERE d.expDate > :date')
            ->setParameters('date', 'now()');*/
   return $query->getOneOrNullResult();
    }
}
